from __future__ import annotations

from datetime import date, datetime
from decimal import Decimal
from typing import Protocol

from quant_platform.domain.entities import (
    DataCoverage,
    MarketBar,
    PointInTimeDataset,
    PointInTimeObservation,
    PointInTimeCoverage,
    ResearchAsset,
    UniverseMembership,
    DailyResearchReport,
    KnowledgeDocument,
    KnowledgeChunk,
    RagQueryAudit,
    SchedulerJobRun,
    AutomationSchedule,
    NotificationDelivery,
    OAuthLoginState,
    PlatformUser,
    UserSession,
    PaperAccount,
    PaperFill,
    PaperOrder,
    PaperPosition,
    BrokerExecutionAudit, PromotionReview, ShadowOrder,
    ResearchExperiment,
    FeatureDefinition,
    FeatureValue,
    FeatureRevision,
    LabelValue,
    StoreCoverage,
    RegimeState,
    FactorResearchResult,
    BacktestArtifact,
    BacktestRun,
    EnsembleArtifact,
    EnsembleRun,
    PortfolioArtifact,
    PortfolioRun,
    ModelExperiment,
    ModelPrediction,
    ModelRegistryEntry,
    ModelDriftSnapshot,
    DataQualitySnapshot,
    DailyDecision,
    TaiwanDataRecord,
    TaiwanDataCoverage,
    ModelExplanation,
    MacroObservation,
    ResearchFailureCase,
)


class ResearchExperimentRepository(Protocol):
    def count(self) -> int: ...

    def list_recent(self, limit: int = 5) -> list[ResearchExperiment]: ...

    def save(self, experiment: ResearchExperiment) -> int: ...

    def get_latest(self, name: str, experiment_type: str) -> ResearchExperiment | None: ...


class ResearchFailureCaseRepository(Protocol):
    def record(self, value: ResearchFailureCase) -> ResearchFailureCase: ...

    def list_recent(self, limit: int = 50) -> list[ResearchFailureCase]: ...

    def resolve(self, case_key: str, verification: str) -> ResearchFailureCase: ...


class ShadowTradingRepository(Protocol):
    def save(self, order: ShadowOrder) -> int: ...

    def get_order(self, order_id: int) -> ShadowOrder | None: ...

    def get_decision(
        self, symbol: str, algorithm: str, experiment_id: int, decision_time: datetime
    ) -> ShadowOrder | None: ...

    def list_orders(self, limit: int = 200) -> list[ShadowOrder]: ...

    def list_pending(self) -> list[ShadowOrder]: ...

    def update(self, order: ShadowOrder) -> None: ...


class PromotionRepository(Protocol):
    def save_review(self, review: PromotionReview) -> int: ...

    def update_review(self, review: PromotionReview) -> None: ...

    def get_review(self, review_id: int) -> PromotionReview | None: ...

    def find_review(
        self, symbol: str, algorithm: str, experiment_id: int, policy_version: str
    ) -> PromotionReview | None: ...

    def list_reviews(self, limit: int = 200) -> list[PromotionReview]: ...

    def save_execution(self, audit: BrokerExecutionAudit) -> int: ...

    def get_execution_by_client_id(self, client_order_id: str) -> BrokerExecutionAudit | None: ...

    def list_executions(self, limit: int = 200) -> list[BrokerExecutionAudit]: ...


class DatabaseProbe(Protocol):
    def ping(self) -> bool: ...


class MarketDataProvider(Protocol):
    name: str

    def fetch_daily_bars(
        self, symbol: str, market: str, start: datetime, end: datetime
    ) -> list[MarketBar]: ...


class MarketBarRepository(Protocol):
    def add_missing(self, bars: list[MarketBar]) -> int: ...

    def list_coverage(self) -> list[DataCoverage]: ...

    def latest_event_time(self, symbol: str, interval: str, source: str) -> datetime | None: ...

    def list_bars(
        self,
        symbol: str,
        interval: str = "1d",
        source: str | None = None,
        as_of: datetime | None = None,
    ) -> list[MarketBar]: ...

    def list_bars_for_symbols(
        self,
        symbols: list[str],
        interval: str = "1d",
        start: datetime | None = None,
        end: datetime | None = None,
        as_of: datetime | None = None,
    ) -> dict[str, list[MarketBar]]: ...

    def count_daily_sessions(
        self, market: str | None = None, as_of: datetime | None = None
    ) -> dict[str, int]: ...

    def latest_closes(
        self, symbols: list[str], as_of: datetime | None = None
    ) -> dict[str, float]: ...


class PointInTimeDataRepository(Protocol):
    def upsert_datasets(self, values: list[PointInTimeDataset]) -> None: ...
    def list_datasets(self, enabled: bool | None = None) -> list[PointInTimeDataset]: ...
    def get_dataset(self, dataset_key: str) -> PointInTimeDataset | None: ...
    def add_revisions(self, values: list[PointInTimeObservation]) -> int: ...
    def list_observations(
        self,
        dataset_key: str,
        entity_id: str | None = None,
        start: datetime | None = None,
        end: datetime | None = None,
        as_of: datetime | None = None,
        limit: int | None = None,
    ) -> list[PointInTimeObservation]: ...
    def list_coverage(self) -> list[PointInTimeCoverage]: ...


class MacroDataRepository(Protocol):
    def add_revisions(self, values: list[MacroObservation]) -> int: ...
    def list_latest(self, series_id: str | None = None) -> list[MacroObservation]: ...


class ResearchUniverseRepository(Protocol):
    def list_all(self) -> list[ResearchAsset]: ...

    def list_active(self, market: str | None = None) -> list[ResearchAsset]: ...

    def get(self, symbol: str) -> ResearchAsset | None: ...

    def add(self, asset: ResearchAsset) -> ResearchAsset: ...

    def set_active(self, symbol: str, active: bool) -> bool: ...

    def update_metadata(self, symbol: str, **values: object) -> bool: ...

    def upsert_memberships(self, values: list[UniverseMembership]) -> int: ...

    def list_memberships(self, market: str | None = None) -> list[UniverseMembership]: ...

    def list_members_on(self, effective_date: date, market: str | None = None) -> list[UniverseMembership]: ...


class ResearchKnowledgeRepository(Protocol):
    def save_report(self, report: DailyResearchReport) -> int: ...
    def list_reports(self, market: str | None = None, limit: int = 30) -> list[DailyResearchReport]: ...
    def upsert_documents(self, values: list[KnowledgeDocument]) -> int: ...
    def list_documents(self) -> list[KnowledgeDocument]: ...
    def remove_documents(self, document_keys: list[str]) -> int: ...
    def list_chunks(self, document_key: str | None = None) -> list[KnowledgeChunk]: ...
    def replace_chunks(self, document_key: str, values: list[KnowledgeChunk]) -> int: ...
    def save_query_audit(self, value: RagQueryAudit) -> int: ...
    def list_query_audits(self, limit: int = 30) -> list[RagQueryAudit]: ...


class SchedulerJobRunRepository(Protocol):
    def start(self, job_name: str, market: str, started_at: datetime) -> int: ...

    def finish(
        self,
        run_id: int,
        status: str,
        completed_at: datetime,
        metrics_json: str,
        error: str | None,
    ) -> None: ...

    def update_progress(self, run_id: int, metrics_json: str) -> None: ...

    def fail_stale_running(
        self, cutoff: datetime, completed_at: datetime
    ) -> int: ...

    def list_recent(self, limit: int = 20) -> list[SchedulerJobRun]: ...

    def latest_succeeded(
        self, job_name: str, market: str, since: datetime
    ) -> SchedulerJobRun | None: ...


class AutomationRepository(Protocol):
    def upsert_schedule(self, value: AutomationSchedule) -> None: ...

    def get_schedule(self, job_key: str) -> AutomationSchedule | None: ...

    def list_schedules(self) -> list[AutomationSchedule]: ...

    def save_delivery(self, value: NotificationDelivery) -> int: ...

    def list_deliveries(self, limit: int = 20) -> list[NotificationDelivery]: ...


class ExecutionLockManager(Protocol):
    def acquire(self, key: str, ttl_seconds: int) -> str | None: ...

    def release(self, key: str, token: str) -> None: ...

    def ping(self) -> bool: ...

    @property
    def backend(self) -> str: ...


class AuthenticationRepository(Protocol):
    def save_login_state(self, value: OAuthLoginState) -> None: ...

    def consume_login_state(
        self, state_hash: str, browser_nonce_hash: str, now: datetime
    ) -> OAuthLoginState | None: ...

    def upsert_user(self, value: PlatformUser) -> PlatformUser: ...

    def save_session(self, value: UserSession) -> None: ...

    def user_for_session(self, token_hash: str, now: datetime) -> PlatformUser | None: ...

    def revoke_session(self, token_hash: str, now: datetime) -> None: ...


class PaperTradingRepository(Protocol):
    def ensure_account(self, name: str, initial_cash: Decimal, now: datetime) -> PaperAccount: ...

    def get_account(self, account_id: int) -> PaperAccount | None: ...

    def save_order(self, value: PaperOrder) -> PaperOrder: ...

    def get_order(self, order_id: int, account_id: int) -> PaperOrder | None: ...

    def list_orders(self, account_id: int, limit: int = 100) -> list[PaperOrder]: ...

    def list_pending_orders(self, account_id: int) -> list[PaperOrder]: ...

    def cancel_order(self, order_id: int, account_id: int, now: datetime) -> bool: ...

    def reject_order(
        self, order_id: int, account_id: int, reason: str, now: datetime
    ) -> bool: ...

    def list_positions(self, account_id: int) -> list[PaperPosition]: ...

    def list_fills(self, account_id: int, limit: int = 100) -> list[PaperFill]: ...

    def execute_fill(
        self, order: PaperOrder, fill: PaperFill, account: PaperAccount,
        position: PaperPosition,
    ) -> None: ...


class FeatureLabelStoreRepository(Protocol):
    def register_definitions(self, definitions: list[FeatureDefinition]) -> None: ...

    def list_definitions(self) -> list[FeatureDefinition]: ...

    def upsert_features(self, values: list[FeatureValue]) -> int: ...

    def add_feature_revisions(self, values: list[FeatureRevision]) -> int: ...

    def list_feature_revisions(
        self,
        symbols: list[str] | None = None,
        feature_names: list[str] | None = None,
        as_of: datetime | None = None,
        limit: int | None = None,
    ) -> list[FeatureRevision]: ...

    def upsert_labels(self, values: list[LabelValue]) -> int: ...

    def feature_coverage(self) -> list[StoreCoverage]: ...

    def label_coverage(self) -> list[StoreCoverage]: ...

    def list_features(
        self, symbols: list[str], feature_names: list[str] | None = None
    ) -> list[FeatureValue]: ...

    def list_latest_features(
        self, symbols: list[str], feature_names: list[str], as_of: datetime
    ) -> list[FeatureValue]: ...

    def list_labels(
        self, symbols: list[str], label_names: list[str] | None = None
    ) -> list[LabelValue]: ...

    def list_latest_labels(
        self, symbols: list[str], label_names: list[str]
    ) -> list[LabelValue]: ...


class RegimeFactorResearchRepository(Protocol):
    def upsert_regimes(self, values: list[RegimeState]) -> int: ...

    def list_regimes(self, symbol: str | None = None) -> list[RegimeState]: ...

    def upsert_factor_results(self, values: list[FactorResearchResult]) -> int: ...

    def list_factor_results(self, market: str | None = None) -> list[FactorResearchResult]: ...


class BacktestResearchRepository(Protocol):
    def save(self, artifact: BacktestArtifact) -> int: ...

    def list_runs(self, market: str | None = None) -> list[BacktestRun]: ...

    def get(self, run_id: int) -> BacktestArtifact | None: ...


class EnsembleResearchRepository(Protocol):
    def save(self, artifact: EnsembleArtifact) -> int: ...

    def list_runs(self, market: str | None = None) -> list[EnsembleRun]: ...

    def get(self, run_id: int) -> EnsembleArtifact | None: ...


class PortfolioResearchRepository(Protocol):
    def save(self, artifact: PortfolioArtifact) -> int: ...

    def list_runs(self, market: str | None = None) -> list[PortfolioRun]: ...

    def get(self, run_id: int) -> PortfolioArtifact | None: ...


class ModelResearchRepository(Protocol):
    def save(self, experiment: ModelExperiment) -> int: ...

    def list_runs(self, market: str | None = None) -> list[ModelExperiment]: ...

    def get(self, run_id: int) -> ModelExperiment | None: ...

    def save_predictions(self, values: list[ModelPrediction]) -> int: ...

    def list_predictions(self, market: str | None = None, symbol: str | None = None) -> list[ModelPrediction]: ...

    def list_predictions_for_experiments(
        self, experiment_ids: list[int]
    ) -> list[ModelPrediction]: ...

    def prediction_coverage(self, experiment_id: int) -> tuple[int, int]: ...

    def save_explanations(self, values: list[ModelExplanation]) -> int: ...

    def list_explanations(
        self, market: str | None = None, symbol: str | None = None
    ) -> list[ModelExplanation]: ...


class ModelGovernanceRepository(Protocol):
    def save_entry(self, entry: ModelRegistryEntry) -> int: ...

    def update_entry(self, entry: ModelRegistryEntry) -> None: ...

    def get_entry(self, entry_id: int) -> ModelRegistryEntry | None: ...

    def get_by_experiment(self, experiment_id: int) -> ModelRegistryEntry | None: ...

    def list_entries(self, market: str | None = None) -> list[ModelRegistryEntry]: ...

    def save_drift(self, snapshot: ModelDriftSnapshot) -> int: ...

    def latest_drift(self, entry_id: int) -> ModelDriftSnapshot | None: ...

    def list_drift(self, entry_id: int | None = None, limit: int = 500) -> list[ModelDriftSnapshot]: ...


class DataQualityRepository(Protocol):
    def save(self, snapshot: DataQualitySnapshot) -> int: ...

    def latest(self, market: str, stage: str = "full") -> DataQualitySnapshot | None: ...

    def list_snapshots(
        self, market: str | None = None, stage: str | None = None, limit: int = 100
    ) -> list[DataQualitySnapshot]: ...


class DailyDecisionRepository(Protocol):
    def upsert(self, values: list[DailyDecision]) -> int: ...

    def list_latest(self, market: str | None = None) -> list[DailyDecision]: ...

    def list_history(
        self, market: str | None = None, limit: int | None = None
    ) -> list[DailyDecision]: ...

    def get_latest(self, symbol: str) -> DailyDecision | None: ...


class ProviderAccessBlockedError(RuntimeError):
    """A provider rejected the configured access tier; retrying will not help."""


class TaiwanDataProvider(Protocol):
    name: str

    def fetch(
        self, dataset: str, symbol: str, start: datetime, end: datetime
    ) -> list[TaiwanDataRecord]: ...


class TaiwanDataRepository(Protocol):
    def add_revisions(self, values: list[TaiwanDataRecord]) -> int: ...

    def list_records(
        self,
        dataset: str | None = None,
        symbol: str | None = None,
        as_of: datetime | None = None,
    ) -> list[TaiwanDataRecord]: ...

    def list_coverage(self) -> list[TaiwanDataCoverage]: ...

    def list_latest(self, symbol: str | None = None) -> list[TaiwanDataRecord]: ...

    def latest_event_time(self, dataset: str, symbol: str, source: str) -> datetime | None: ...
